bboard/bboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='')),
]
if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

bboard/main/urls.py
from django.urls import path
from .views import index

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
]

bboard/main/models.py
from django.db import models

# Create your models here.

bboard/main/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'main/index.html')

bboard/main/templates/layout/basic.html
{% load bootstrap4 %}
{% load static %}
<!--<!DOCTYPE html>-->
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text-html" charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no ">
    <title>{% block title %}Главная{% endblock %}-Доска объявлений</title>
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
    {% bootstrap_javascript jquery='slim' %}
</head>
<body class="container-fluid">

    <header class="mb-4">
       <h1 class="display-1 text-center">Объявления</h1>
    </header>
    <div class="row">
        <ul class="col nav justify-content-end border">
            <li class="nav-item"><a href="#" class="nav-link">Регистрация</a></li>
            <li class="nav-item dropdown"><a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="True" aria-expanded="False">Профиль</a>
        <div class="dropdown-menu">
            <a href="#" class="dropdown-item">Мои объявления</a>
            <a href="#" class="dropdown-item">Изменить личные данные</a>
            <a href="#" class="dropdown-item">Изменить пароль</a>
            <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">Выйти</a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">Удалить</a>
        </div>
            <li class="nav-item"><a href="#" class="nav-link">Вход</a></li>
        </ul>
    </div>
    <div class="row">
        <nav class="col-md-auto nav-flex-column border">
            <a href="{% url 'main:index' %}" class="nav-link root">Главная</a>
            <span class="nav-link root font-weight-bold">Недвижимость</span>
            <a href="#" class="nav-link ">Жилье</a>
            <a href="#" class="nav-link ">Склады</a>
            <a href="#" class="nav-link ">Гаражи</a>
            <span class="nav-link root font-weight-bold">Транспорт</span>
            <a href="#" class="nav-link ">Легковой</a>
            <a href="#" class="nav-link ">Грузовой</a>
        </nav>
        <section class="col border py-2">
            {% bootstrap_messages %}
            {%block content %}
            {% endblock %}
        </section>
    </div>
    <footer class="mt-3">
        <p class="text-right font-italic">&copy;Читатели, 2018 г.</p>
    </footer>
</body>
</html>

bboard/main/templates/main/index.html
{% extends 'layout/basic.html' %}
{% block content %}
<h2>Последние десять объявлений</h2>
{% endblock %}